services:
  postgres:
    image: postgres:15
    container_name: yaplo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: yaplo_user
      POSTGRES_PASSWORD: yaplo_password
      POSTGRES_DB: yaplo_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: